# Generated by Django 3.1.4 on 2020-12-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_time_calc', '0002_dummy_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('time_rest', models.TimeField()),
                ('key_values', models.CharField(choices=[('-', '-'), ('A', 'Abwesend'), ('K', 'Krank'), ('U', 'Urlaub')], default='-', max_length=10)),
                ('user_created', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'user_created', 'time_start'],
            },
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
