# Generated by Django 3.1.4 on 2020-12-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_time_calc', '0003_auto_20201219_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='time_worked',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
