# Generated by Django 3.1.4 on 2020-12-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_time_calc', '0004_timeentry_time_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='time_worked',
        ),
    ]
