# Generated by Django 3.1.4 on 2020-12-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_time_calc', '0006_auto_20201219_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='time_rest',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
